server:
    port: 8882

spring:
    application:
        name: order-service
    profiles:
        include: "dev"
    jpa:
        hibernate:
            ddl-auto: create-drop
        show-sql: true
        generate-ddl: true
        defer-datasource-initialization: true
    sql:
        init:
            mode: always
eureka:
    instance:
        instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    client:
        register-with-eureka: true
        fetch-registry: true
        service-url:
            defaultZone: http://localhost:8761/eureka
